### ISSUE TITLE
Native image 

### ISSUE THREAD

**Issue by rnayabed** [hakanrw/PNGz-Encryptor#1]
This tool is greater. The startup time and performance can be increased further if you are able to build native images for it across different platforms. You can take a look at [Gluon Client](https://docs.gluonhq.com/client/).

**Comment by hakanrw** [comment]
Hmm, it seems like a very useful tool. As far as I understood, there is no need to include any additional JRE/JAR etc. that I used in my project, it automatically bundles them in the executable. I'm definitely taking a look at it. 
I might update the links once I manage to get this tool working.
